name: Docker Registry w/ UI
description: |
  Run your own Docker Registry with a Web User Interface
version: 1.0.0
category: registry
maintainer: Jamie Curnow <jc@jc21.com>
license: BSD
projectURL: https://github.com/jc21/docker-registry-ui
